### PR TITLE
Committing NumOfWordsInString file into branchDev

### PR DESCRIPTION
**Pull request by mbmtest**
hi master,
I have added one file. Please allow to merge.

Regards
dev

### CODE REVIEW

**Comment by mbm77** [comment]
Hi dev,
Your code looks good. Please go with one more check on that file.

Regards,
master

**Comment by mbmtest** [comment]
Hi master,
I have checked my file and made required changes. Please approve this.

Regards
dev

**Comment by mbm77** [comment]
Hi dev,
I have reviewed code. I will approve.

Regards,
master

**Review by mbm77 — COMMENTED** [review]
hi dev,
Now approved your code.

Regards
master

**Comment by mbm77** [comment]
ok

**Review by mbm77 — CHANGES_REQUESTED** [review]
ok approve

**Review by mbm77 — APPROVED** [review]

**Pull request merged**
